### ISSUE TITLE
5. Неверная реализация метода add в классе CreditAccount при пополнении суммы на карту

### ISSUE THREAD

**Issue by MarkSovchik** [MarkSovchik/TeamProject#5]
## Описание дефекта:
Ошибка кода при не верном добавлении суммы к балансу. Метод add должен увеличивать balance на сумму покупки, а не устанавливать balance равным сумме покупки, это приводит к неверному результату.

## Локация дефекта в CreditAccount, метод Add
https://github.com/MarkSovchik/TeamProject/blob/0733692e992eaac964d28b19c8721d6c70275c75/src/main/java/ru/topacademy/javaqateamproject/CreditAccount.java#L69

## Локация дефекта в тесте CreditAccountTest
https://github.com/MarkSovchik/TeamProject/blob/0733692e992eaac964d28b19c8721d6c70275c75/src/test/java/ru/topacademy/javaqateamproject/CreditAccountTest.java#L18

## Шаги воспроизведения
1.Открыть [код программы](https://github.com/MarkSovchik/TeamProject/blob/main/src/test/java/ru/topacademy/javaqateamproject/CreditAccountTest.java) в IDEA.
2.Выбрать тест shouldAddToPositiveBalance().
3.Запустить процесс отладки кода(debug).
4.Проанализировать результат.

**Ожидаемый результат:** Баланс счета должен увеличиться на добавленную сумму.
**Фактический результат:** Баланс счета становится равным сумме покупки.

## Скриншот
![image](https://github.com/user-attachments/assets/696d338e-8366-4328-b160-183a8a7a0a70)

## Окружение
Операционная система: Windows 11
IDE: IntelliJ IDEA Community Edition 2024.1.1
Java: Open JDK-11

**Comment by anastasya-777** [comment]
#5
