### ISSUE TITLE
6. Неверная реализация конструктора CreditAccount в классе CreditAccount при написании кода.

### ISSUE THREAD

**Issue by MarkSovchik** [MarkSovchik/TeamProject#6]
## Описание
В конструкторе CreditAccount не проверяются все переданные параметры, проверяется только **rate** на отрицательное значение, но также необходимо проверить **initialBalance** и **creditLimit** на отрицательность, так как они тоже должны быть неотрицательными.

## Локация дефекта в классе CreditAccount в конструкторе CreditAccount
https://github.com/MarkSovchik/TeamProject/blob/3300cb8b1b636a7ed1753dfbbcc1deef6526a9f7/src/main/java/ru/topacademy/javaqateamproject/CreditAccount.java#L19

```
public CreditAccount(int initialBalance, int creditLimit, int rate) {
    if (rate <= 0) {
        throw new IllegalArgumentException(
                "Накопительная ставка не может быть отрицательной, а у вас: " + rate
        );
    }
    this.balance = initialBalance;
    this.creditLimit = creditLimit;
    this.rate = rate;
}
```

## Шаги воспроизведения
Открыть [код программы](https://github.com/MarkSovchik/TeamProject/blob/CreditBranch/src/main/java/ru/topacademy/javaqateamproject/CreditAccount.java) в IDEA.
Выбрать конструктор public CreditAccount (int initialBalance, int creditLimit, int rate)
Проанализировать код.

**Ожидаемый результат:** Конструктор должен проверять все переданные параметры на отрицательное значение.
**Фактический результат:** Конструктор проверяет только один параметр rate на отрицательное значение, что может привести к неправильной работе программы.

## Скриншот
![image](https://github.com/user-attachments/assets/92cc1dca-7b8c-4168-ad86-becbe0ef9a9a)

## Окружение
Операционная система: Windows 11
IDE: IntelliJ IDEA Community Edition 2024.1.1
Java: Open JDK-11

**Comment by anastasya-777** [comment]
#6
