### ISSUE TITLE
7. Неверное изменение баланса в методе "pay" класса "CreditAccount" при оплате.

### ISSUE THREAD

**Issue by MarkSovchik** [MarkSovchik/TeamProject#7]
## Описание
Метод **pay** класса CreditAccount не правильно изменяет баланс при попытке оплаты превышающей кредитный лимит, баланс счета должен оставаться неизменным, а метод **pay** устанавливает его в отрицательное значение, что не соответствует описанию метода.
## Локация дефекта класса CreditAccount в методе pay
https://github.com/MarkSovchik/TeamProject/blob/8e57b244709a33f23cc92f7b55aaa0b5de7fec54/src/main/java/ru/topacademy/javaqateamproject/CreditAccount.java#L40

## Шаги воспроизведения
1. Открыть тестовый класс [CreditAccountTest](https://github.com/MarkSovchik/TeamProject/blob/CreditBranch/src/test/java/ru/topacademy/javaqateamproject/CreditAccountTest.java) в IDEA.
2. Запустить тест "testPayExceedingCreditLimitBalanceUnchanged()"
3. Проанализировать результат теста.

**Ожидаемый результат:** Баланс не изменяется.
**Фактический результат:** Баланс устанавливается в отрицательное значение.

## Ссылка на тест

https://github.com/MarkSovchik/TeamProject/blob/ed23d371e9e224c48e346f9d1b972a92bef64f85/src/test/java/ru/topacademy/javaqateamproject/CreditAccountTest.java#L65
## Скриншот

![image](https://github.com/user-attachments/assets/140d8d36-68c8-4f56-85b3-40b890d4fac7)

## Окружение
Операционная система: Windows 11
IDE: IntelliJ IDEA Community Edition 2024.1.3
Java: Open JDK-11

**Comment by anastasya-777** [comment]
#7
