### ISSUE TITLE
8. Неверный расчет процентов при реализации метода yearChange в классе CreditAccount.

### ISSUE THREAD

**Issue by MarkSovchik** [MarkSovchik/TeamProject#8]
## Описание
Ошибка кода в неверном расчете процентов для положительного баланса. Метод yearChange должен правильно рассчитывать проценты для отрицательного баланса, а для положительного баланса проценты не должны начисляться.
## Локация дефекта

https://github.com/MarkSovchik/TeamProject/blob/8e57b244709a33f23cc92f7b55aaa0b5de7fec54/src/main/java/ru/topacademy/javaqateamproject/CreditAccount.java#L82
##  Шаги для воспроизведения
1. Открыть тестовый класс [CreditAccountTest](https://github.com/MarkSovchik/TeamProject/blob/CreditBranch/src/test/java/ru/topacademy/javaqateamproject/CreditAccountTest.java) в IDEA.
2. Запустить тест testYearChangeWithPositiveBalance().
3. Проанализировать результат выполнения теста.

**Ожидаемый результат:** Метод не должен рассчитывать проценты для положительного баланса и возвращать "0".
**Фактический результат:** Метод начисляет проценты при положительном балансе.

## Ссылка на тест
https://github.com/MarkSovchik/TeamProject/blob/08a727c4b63e6eea08e1f75254bf2e01eda1658f/src/test/java/ru/topacademy/javaqateamproject/CreditAccountTest.java#L75
## Скриншот

![image](https://github.com/user-attachments/assets/e6a3129d-7e6d-4ea4-9253-06b8fee26c7f)

## Окружение:
Операционная система: Windows 11
IDE: IntelliJ IDEA Community Edition 2024.1.1
Java: Открытый JDK-11

**Comment by anastasya-777** [comment]
#8
