### ISSUE TITLE
9. Неверная реализация условия в конструкторе класса CreditAccount при проверки процентной ставки.

### ISSUE THREAD

**Issue by MarkSovchik** [MarkSovchik/TeamProject#9]
## Описание
При попытке создания объекта CreditAccount с нулевой процентной ставкой выбрасывается исключение IllegalArgumentException с сообщением "Накопительная ставка не может быть отрицательной, а у вас: 0". Но по условиям в описании метода, нулевая процентная ставка должна быть допустима.

## Локация дефекта

https://github.com/MarkSovchik/TeamProject/blob/3300cb8b1b636a7ed1753dfbbcc1deef6526a9f7/src/main/java/ru/topacademy/javaqateamproject/CreditAccount.java#L20

## Шаги для воспроизведения
1. Открыть тестовый класс [CreditAccountTest](https://github.com/MarkSovchik/TeamProject/blob/CreditBranch/src/test/java/ru/topacademy/javaqateamproject/CreditAccountTest.java) в IDEA.
2. Запустить тест testCreditAccountCreationWithZeroRate()
3. Проанализировать результат.

**Ожидаемый результат:** Объект CreditAccount должен быть успешно создан без выброса исключений.
**Фактический результат:** Выбрасывается исключение IllegalArgumentException с сообщением "Накопительная ставка не может быть отрицательной, а у вас: 0".

## Ссылка на тест
https://github.com/MarkSovchik/TeamProject/blob/8e57b244709a33f23cc92f7b55aaa0b5de7fec54/src/test/java/ru/topacademy/javaqateamproject/CreditAccountTest.java#L61
## Скриншот

![image](https://github.com/user-attachments/assets/9b681032-d723-46e9-b692-6db9cd88cd73)

## Окружение
Операционная система: Windows 11
IDE: IntelliJ IDEA Community Edition 2024.1.1
Java: Открытый JDK-11

**Comment by anastasya-777** [comment]
#9
